### ISSUE TITLE
Nothing gets generated

### ISSUE THREAD

**Issue by bartkummel** [Optravis-LLC/jooq-gradle#25]
Configured everything as described. Everything seems to work, because:
- If there's a syntax error in the SQL migration, the build fails (so Flyway works)
- If Docker is down, the build fails (so Docker works)
- On a first build, I first see a couple of connection failures, and eventually the build continues without error (so Postgres is online)
- Gradle says the generate step completed. When I change something in the migration, I can see the generation step is not up to date

However, no code gets generated. Now what?

**Comment by jcornaz** [comment]
Hi,

Do you define the `group` in your gradle script?

Here's a working example for reference: https://github.com/Optravis-LLC/jooq-gradle/blob/60666c498dbc279bda53f82aba79b02f24e6ddd7/examples/default_config/build.gradle.kts#L7

If it's not that, then it would be nice if you can try to provide a minimal reproducer, as I don't see why the task would be successful (and not up-to-date) without generating code.

**Comment by bartkummel** [comment]
Thanks for your quick reply!
- The `group` was missing in my Gradle script indeed.
- But I also needed to set the DB schema, using: `jooqDbConfig = JooqDatabaseConfig.postgres(schema = "myschema")`

Anyway, it works now. Awesome! Thanks for your help.
