### ISSUE TITLE
Have a fallback package name in case the `group` is not defined.

### ISSUE THREAD

**Issue by jcornaz** [Optravis-LLC/jooq-gradle#26]
I don't yet know if that would have helped for #25, but forgetting the `group` certainly did trip me up once, and we should have a better default in case it is not defined.

**Comment by ursjoss** [comment]
As the schema also needs to be set (see [here](https://github.com/Optravis-LLC/jooq-gradle/issues/25#issuecomment-2222178088), we should maybe also have a default setting for the schema (maybe `public`).

**Comment by jcornaz** [comment]
> As the schema also needs to be set (see [here](https://github.com/Optravis-LLC/jooq-gradle/issues/25#issuecomment-2222178088)), we should maybe also have a default setting for the schema (maybe `public`).

Isn't that already the default?

https://github.com/Optravis-LLC/jooq-gradle/blob/60666c498dbc279bda53f82aba79b02f24e6ddd7/src/main/kotlin/com/optravis/jooq/gradle/Config.kt#L90

I don't need specify the schema in my setup (see example: https://github.com/Optravis-LLC/jooq-gradle/blob/60666c498dbc279bda53f82aba79b02f24e6ddd7/examples/default_config/build.gradle.kts)

I assume @bartkummel needed to specify the schema, precisely because he's not using the `public` schema?

**Comment by bartkummel** [comment]
That's right, I used a custom schema. Maybe good to add an example for that to one of the examples or add it to the README? It's not hard, but I had to dig around the sources to find out how exactly I should configure it.
