### ISSUE TITLE
docs: document the different configuration options

### ISSUE THREAD

**Issue by ursjoss** [Optravis-LLC/jooq-gradle#29]
in the README or alternatively in a dedicated documentation file. Specifically requested for the `schema` configuration (as an example) [here](https://github.com/Optravis-LLC/jooq-gradle/issues/26#issuecomment-2222404997).

as a starter, until we get to it, my config from another project:

```
@OptIn(ExperimentalJooqGeneratorConfig::class)
jooqGenerator {
    val dbUserName = props.getProperty("spring.datasource.hikari.username")
    val dbPassword = props.getProperty("spring.datasource.hikari.password")
    containerConfig = ContainerConfig(
        image = "postgres:15.4",
        port = 5432,
        environment = mapOf(
            "POSTGRES_DB" to props.getProperty("db.name"),
            "POSTGRES_USER" to dbUserName,
            "POSTGRES_PASSWORD" to dbPassword,
        ),
    )
    jooqDbConfig = JooqDatabaseConfig.postgres(recordVersionFields = listOf("version"))
    generatorConfig = JooqGeneratorConfig(
        generatorType = GeneratorType.Java,
        deprecateUnknownTypes = true,
        javaTimeTypes = false,
        daos = false,
        pojos = false,
    )
    connectionConfig = DbConnectionConfig(
        user = dbUserName,
        password = dbPassword,
        urlTemplate = "jdbc:postgresql://localhost:{{port}}/${props.getProperty("db.name")}",
    )
    packageName = "ch.difty.scipamato.core.db"
}
````

**Comment by ursjoss** [comment]
@jcornaz What's your opinion: Shall we enhance the example `examples/with_config` folder to cover every possible option? Or do we keep that rather minimal and maintain a document for the options?

**Comment by jcornaz** [comment]
> @jcornaz What's your opinion: Shall we enhance the example `examples/with_config` folder to cover every possible option? Or do we keep that rather minimal and maintain a document for the options?

Here's my opinion: #30 :smiley_cat:
